# coding: utf-8

"""
    REST API for the EK80 Echo Sounder

    This API is for internal Simrad/Kongsberg Maritime use only.  The API, and the documentation of it, is currently under construction and is subject to change without further notice  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ek80_param_client
from ek80_param_client.api.ownship_api import OwnshipApi  # noqa: E501
from ek80_param_client.rest import ApiException


class TestOwnshipApi(unittest.TestCase):
    """OwnshipApi unit test stubs"""

    def setUp(self):
        self.api = ek80_param_client.api.ownship_api.OwnshipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ownship_get_dimension(self):
        """Test case for ownship_get_dimension

        """
        pass

    def test_ownship_get_drop_keel_offset(self):
        """Test case for ownship_get_drop_keel_offset

        Get Drop keel offset  # noqa: E501
        """
        pass

    def test_ownship_get_installed_transducers(self):
        """Test case for ownship_get_installed_transducers

        Get a list of all installed transducers  # noqa: E501
        """
        pass

    def test_ownship_get_manual_settings(self):
        """Test case for ownship_get_manual_settings

        Get a list of all manual settings  # noqa: E501
        """
        pass

    def test_ownship_get_manual_speed_setting(self):
        """Test case for ownship_get_manual_speed_setting

        Get manual speed settings  # noqa: E501
        """
        pass

    def test_ownship_get_motion(self):
        """Test case for ownship_get_motion

        """
        pass

    def test_ownship_get_navigation(self):
        """Test case for ownship_get_navigation

        """
        pass

    def test_ownship_get_ownship(self):
        """Test case for ownship_get_ownship

        """
        pass

    def test_ownship_get_water_level(self):
        """Test case for ownship_get_water_level

        Get water level offset  # noqa: E501
        """
        pass

    def test_ownship_set_drop_keel_offset(self):
        """Test case for ownship_set_drop_keel_offset

        Set Drop keel offset  # noqa: E501
        """
        pass

    def test_ownship_set_manual_speed_setting(self):
        """Test case for ownship_set_manual_speed_setting

        Set manual speed setting  # noqa: E501
        """
        pass

    def test_ownship_set_transducer_installation(self):
        """Test case for ownship_set_transducer_installation

        Sets a new intallation for a given transducer  # noqa: E501
        """
        pass

    def test_ownship_set_water_level(self):
        """Test case for ownship_set_water_level

        Set water level offset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
