# coding: utf-8

"""
    REST API for the EK80 Echo Sounder

    This API is for internal Simrad/Kongsberg Maritime use only.  The API, and the documentation of it, is currently under construction and is subject to change without further notice  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ek80_param_client
from ek80_param_client.api.ping_info_api import PingInfoApi  # noqa: E501
from ek80_param_client.rest import ApiException


class TestPingInfoApi(unittest.TestCase):
    """PingInfoApi unit test stubs"""

    def setUp(self):
        self.api = ek80_param_client.api.ping_info_api.PingInfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_executed_pings_get_executed_ping(self):
        """Test case for executed_pings_get_executed_ping

        """
        pass


if __name__ == '__main__':
    unittest.main()
