# coding: utf-8

"""
    REST API for the EK80 Echo Sounder

    This API is for internal Simrad/Kongsberg Maritime use only.  The API, and the documentation of it, is currently under construction and is subject to change without further notice  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ek80_param_client
from ek80_param_client.api.transducer_capabilities_api import TransducerCapabilitiesApi  # noqa: E501
from ek80_param_client.rest import ApiException


class TestTransducerCapabilitiesApi(unittest.TestCase):
    """TransducerCapabilitiesApi unit test stubs"""

    def setUp(self):
        self.api = ek80_param_client.api.transducer_capabilities_api.TransducerCapabilitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_transducer_capabilities_get(self):
        """Test case for transducer_capabilities_get

        """
        pass

    def test_transducer_capabilities_get_transducer_capability(self):
        """Test case for transducer_capabilities_get_transducer_capability

        """
        pass


if __name__ == '__main__':
    unittest.main()
