# coding: utf-8

"""
    REST API for the EK80 Echo Sounder

    This API is for internal Simrad/Kongsberg Maritime use only.  The API, and the documentation of it, is currently under construction and is subject to change without further notice  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ek80_param_client
from ek80_param_client.models.transceiver_capabilities import TransceiverCapabilities  # noqa: E501
from ek80_param_client.rest import ApiException


class TestTransceiverCapabilities(unittest.TestCase):
    """TransceiverCapabilities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransceiverCapabilities(self):
        """Test TransceiverCapabilities"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ek80_param_client.models.transceiver_capabilities.TransceiverCapabilities()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
