# coding: utf-8

"""
    REST API for setting up data subscriptions on the EK80 Echo Sounder

    The API, and the documentation of it, is currently under construction and is subject to change without further notice  # How to start data output  1. Create a subscription  2. Create a communication end point  3. Add the subscription to the communication end point    A link example, [kongsberg.com](http://www.kongsberg.com).  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ek80_data_client
from ek80_data_client.api.adcp_velocity_subscriptions_api import AdcpVelocitySubscriptionsApi  # noqa: E501
from ek80_data_client.rest import ApiException


class TestAdcpVelocitySubscriptionsApi(unittest.TestCase):
    """AdcpVelocitySubscriptionsApi unit test stubs"""

    def setUp(self):
        self.api = ek80_data_client.api.adcp_velocity_subscriptions_api.AdcpVelocitySubscriptionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_adcp_velocity_subscription(self):
        """Test case for create_adcp_velocity_subscription

        Create an adcp data subscription  # noqa: E501
        """
        pass

    def test_delete_adcp_velocity_subscription(self):
        """Test case for delete_adcp_velocity_subscription

        Delete an adcp detection data subscription  # noqa: E501
        """
        pass

    def test_get_adcp_velocity_subscriptions(self):
        """Test case for get_adcp_velocity_subscriptions

        Get all adcp data subscriptions  # noqa: E501
        """
        pass

    def test_get_velocity_adcp_subscription(self):
        """Test case for get_velocity_adcp_subscription

        Get an adcp subscription specification  # noqa: E501
        """
        pass

    def test_update_adcp_velocity_subscription(self):
        """Test case for update_adcp_velocity_subscription

        Update an adcp subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
